# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('chapter', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('marks', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=200)),
                ('q_id', models.CharField(max_length=20)),
            ],
        ),
    ]
