# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainBS', '0002_auto_20180307_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
